# Generated by Django 5.0.3 on 2024-03-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntmeter', '0002_historicalmeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Con_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='historicalmeter',
            name='con_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='historicalmeter',
            name='con_port',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='con_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='con_port',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalmeter',
            name='con_method',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sntmeter.con_method'),
        ),
        migrations.AddField(
            model_name='meter',
            name='con_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sntmeter.con_method'),
        ),
    ]
