# Generated by Django 5.0.3 on 2024-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntmeter', '0003_con_method_historicalmeter_con_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeter',
            name='con_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='con_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
