# Generated by Django 5.0.3 on 2024-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntmeter', '0006_historicalmeter_baud_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeter',
            name='pot_act_dir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmeter',
            name='pot_act_rev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='pot_act_dir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='pot_act_rev',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
