# Generated by Django 5.0.3 on 2024-04-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntmeter', '0007_alter_historicalmeter_pot_act_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeter',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
