# Generated by Django 5.1.1 on 2024-10-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntmeter', '0008_historicalmeter_group_meter_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeter',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meter',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
