# Generated by Django 5.1.1 on 2024-12-08 21:02

import sntmeter.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntmeter', '0009_alter_historicalmeter_name_alter_meter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con_method',
            name='type',
            field=models.CharField(max_length=20, validators=[sntmeter.validators.validar_metodo]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, validators=[sntmeter.validators.validar_nombre]),
        ),
    ]
